# Generated by Django 4.2.4 on 2023-08-19 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "numero_de_demande",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("attente", "En attente"),
                            ("traitement", "En traitement"),
                            ("approuvee", "Approuvée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="attente",
                        max_length=20,
                    ),
                ),
                ("lieu_naissance", models.CharField(max_length=200)),
                ("date_naissance", models.DateField()),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("adresse", models.TextField()),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=200)),
                ("pays", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("identite", "Justificatif d'identité"),
                            ("acte de naissance", "Justificatif de naissance"),
                            ("domicile", "Justificatif de domicile"),
                            ("autorisation", "Autorisation de la personne concernée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(upload_to="documents/")),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_associes",
                        to="justiceApp.demande",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="demande",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demande_associee",
                to="justiceApp.document",
            ),
        ),
        migrations.AddField(
            model_name="demande",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
