# Generated by Django 4.2.4 on 2023-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("justiceApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demande",
            name="document",
        ),
        migrations.RemoveField(
            model_name="demande",
            name="nom",
        ),
        migrations.RemoveField(
            model_name="demande",
            name="prenom",
        ),
        migrations.AddField(
            model_name="demande",
            name="fichier_document_identite",
            field=models.FileField(default="", upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="demande",
            name="justificatif_domicile",
            field=models.FileField(default="", upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="demande",
            name="type_document_identite",
            field=models.CharField(
                choices=[
                    ("passport", "Passeport"),
                    ("acte_naissance", "Acte de naissance"),
                ],
                default="Passport",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
