# Generated by Django 4.2.4 on 2023-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("justiceApp", "0002_remove_demande_document_remove_demande_nom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demande",
            name="type_document_identite",
            field=models.CharField(
                choices=[
                    ("passport", "Passeport"),
                    ("acte_naissance", "Acte de naissance"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
