# Generated by Django 4.2.4 on 2023-08-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="numero_de_telephone",
            new_name="telephone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
