# Generated by Django 4.2.4 on 2023-08-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_rename_numero_de_telephone_user_telephone_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
