# Generated by Django 4.2.4 on 2023-08-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_user_lieu_de_naissance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lieu_de_naissance",
        ),
        migrations.AddField(
            model_name="user",
            name="nationalite",
            field=models.CharField(
                choices=[("etranger", "Étranger"), ("gabon", "Gabonais")],
                default="",
                max_length=20,
            ),
        ),
    ]
