# Generated by Django 4.2.4 on 2023-08-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_remove_user_lieu_de_naissance_user_nationalite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STANDARD_USER", "Utilisateur standard"),
                    ("ADMIN", "Administrateur"),
                ],
                default="STANDARD_USER",
                max_length=20,
            ),
        ),
    ]
